### ISSUE TITLE
Add test cases with larger messages (100 kB, several MB, 10s of MBs)

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-amqp1.0-client#14]
See https://github.com/rabbitmq/rabbitmq-amqp1.0-client/issues/11#issuecomment-353309245. At the very least we can add some test cases in the meantime.

**Comment by kjnilsson** [comment]
[this test](https://github.com/rabbitmq/rabbitmq-amqp1.0-client/blob/master/test/system_SUITE.erl#L370) already tests split transfers against activemq and RabbitMQ.

**Comment by kjnilsson** [comment]
that said there may be some other bug around very large messages.
