### ISSUE TITLE
amqp10_binary_generator not exist

### ISSUE THREAD

**Issue by qiannianshaonian** [rabbitmq/rabbitmq-amqp1.0-client#34]
exception exit: {function_clause,
                        [{amqp10_binary_generator,generate,"a",
                             [{file,"src/amqp10_binary_generator.erl"},
                              {line,86}]},

**Comment by qiannianshaonian** [comment]
when i set amqp10_msg:new(MsgId1, Msg, false)

**Comment by qiannianshaonian** [comment]
@michaelklishin

**Comment by michaelklishin** [comment]
@qiannianshaonian in #33 we asked for a snippet of code and environment details (such as RabbitMQ version or other broker used) that can be used to reproduce. I'm afraid a single exception tuple does not make it any clearer as to what you are trying to do. We also asked that you don't mention team members individually here. If you are looking for help from our team, please cooperate.

**Comment by kjnilsson** [comment]
It is likely the `Msg` isn't the correct type. See type spec here:

https://github.com/rabbitmq/rabbitmq-amqp1.0-client/blob/master/src/amqp10_msg.erl#L263
