### ISSUE TITLE
when  ok = amqp10_client:flow_link_credit(Receiver,1, never)

### ISSUE THREAD

**Issue by qiannianshaonian** [rabbitmq/rabbitmq-amqp1.0-client#35]
I send the first message to reply, but send another message, the server can receive, but the client can not receive the reply. Why?

**Comment by qiannianshaonian** [comment]
@michaelklishin

**Comment by michaelklishin** [comment]
Closing [for the same reason as explained in this comment to #34](https://github.com/rabbitmq/rabbitmq-amqp1.0-client/issues/34#issuecomment-475561165).
