### ISSUE TITLE
consumer 

### ISSUE THREAD

**Issue by qiannianshaonian** [rabbitmq/rabbitmq-amqp1.0-client#36]
Is the amqp0.9 consumer equal to the receiver here?

**Comment by michaelklishin** [comment]
This is an AMQP 1.0 client. [AMQP 0-9-1 and AMQP 1.0 are completely different protocols](https://www.rabbitmq.com/protocols.html), despite the name. See [rabbitmq/rabbitmq-erlang-client](https://github.com/rabbitmq/rabbitmq-erlang-client/) if you need an AMQP 0-9-1 client.
