### ISSUE TITLE
(Mostly) lacking URI parser tests

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-amqp1.0-client#37]
URI parser in this client largely lacks tests. Discovered while QA'ing https://github.com/rabbitmq/rabbitmq-shovel/pull/57.

**Comment by kjnilsson** [comment]
Any particular cases that you found? We can add them to the tests here: https://github.com/rabbitmq/rabbitmq-amqp1.0-client/blob/master/src/amqp10_client.erl#L466

**Comment by michaelklishin** [comment]
I indeed tried to use a path segment.

**Comment by michaelklishin** [comment]
We'll consider this addressed in https://github.com/rabbitmq/rabbitmq-amqp1.0-client/commit/8ef26ead733f5366f8127518a81911c9e64589d1 for now.
